name: EasyElevator
main: main.classes.EasyElevator
version: ${project.version}
commands:
  elv:
    description: Elevator Commands
    usage: /elv
  eelevator:
    description: Elevator Commands
    usage: /eelevator